# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Mateus Nicolas Hechenblaichner Balestrin
tagline:          'A Personal Blog'
description:      'A Data Engineer with a passion for technology'
baseurl:          /

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Google services
# google_analytics: UA-170948634-1

# RSS
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1

paginate:         5

# Custom vars
social:
  github:         
  linkedin:       https://www.linkedin.com/in/mattnhb/
